name: spend_save
description: A personal finance app with envelope budgeting
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # UI & Design
  glassmorphism: ^2.0.0
  font_awesome_flutter: ^10.5.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  fl_chart: ^0.65.0
  
  # Navigation & Structure
  table_calendar: ^3.0.9
  intl: ^0.18.1
  
  # State & Data Management
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  # Fonts Setup
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter_24pt-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

  assets:
    - assets/